name: CxTokens 
version: '${project.version}'
main: ca.cxtokens.CxTokens
api-version: 1.19
authors: [ CKAY9 ]
description: '${project.description}'
commands:
  cxtokens:
    description: Information about CxTokens
  tbal:
    description: Get the balance of you or someone else online
  tstore:
    description: Open up the Token Shop
  tauction:
    description: Open up the Auction House
  ttop:
    description: See who has the most tokens
  tsend:
    description: Send tokens to a player
  treset:
    description: Reset your token count to the starting amount
  tlottery:
    description: Token lottery

